language: objective-c
osx_image: xcode10.2

xcode_workspace: NetKit.xcworkspace
xcode_scheme:
    - NetKit
    - NetKitExample
xcode_sdk: iphonesimulator12.2
#xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

#xcode_configuration: Release
#script:
#  - xcodebuild -workspace NetKit.xcworkspace -scheme NetKit -configuration Release -sdk iphonesimulator11.0
#  - xcodebuild -workspace NetKit.xcworkspace -scheme NetKitExample -configuration Release -sdk iphonesimulator11.0
